// Generated by LiveScript 1.3.1
(function(){
  var blessed, Keyboard;
  blessed = require('blessed');
  Keyboard = (function(){
    Keyboard.displayName = 'Keyboard';
    var prototype = Keyboard.prototype, constructor = Keyboard;
    function Keyboard(screen){
      this.screen = screen;
      this.screen.key(['escape', 'C-c'], function(){
        return process.exit(0);
      });
    }
    return Keyboard;
  }());
  module.exports = Keyboard;
}).call(this);
