// Generated by LiveScript 1.3.1
(function(){
  var wrapper;
  wrapper = 'require! {\n  path\n}\n\nglobal import require \\prelude-ls\nglobal import require \\./src/Helpers\n\n___res___ = do ->\n  goesHere\n\nconsole.log that if ___res___?';
  module.exports = function(it){
    if (!(it != null && it.length)) {
      it = "''";
    }
    return wrapper.toString().replace('goesHere', it);
  };
}).call(this);
