// Generated by LiveScript 1.3.1
(function(){
  var wrapper;
  wrapper = 'require! {\n  path\n}\n\nglobal import require \\prelude-ls\nglobal import require \\lish-std\n\n___res___ = do ->\n  goesHere\n\n# console.log that if ___res___?\nprocess.exit 0';
  module.exports = function(it){
    if (!(it != null && it.length)) {
      it = "''";
    }
    return wrapper.toString().replace('goesHere', it);
  };
}).call(this);
