// Generated by LiveScript 1.3.1
(function(){
  var blessed, Prompt, Interpret, Output, __, LiveShell;
  blessed = require('blessed');
  Prompt = require('./Prompt');
  Interpret = require('./Interpret');
  Output = require('./Output');
  __ = require('underscore');
  LiveShell = (function(){
    LiveShell.displayName = 'LiveShell';
    var prototype = LiveShell.prototype, constructor = LiveShell;
    function LiveShell(){
      this.Init();
    }
    prototype.Init = function(){
      var evaluate, this$ = this;
      this.screen = blessed.screen({
        smartCSR: true,
        cursor: {
          artificial: true,
          shape: 'block',
          color: null
        }
      });
      this.main = blessed.box({
        parent: this.screen,
        left: 0,
        top: 0,
        width: this.screen.width,
        height: this.screen.height
      });
      this.prompt = new Prompt(this.screen, this.main);
      this.interpret = new Interpret(this.screen, this.main);
      this.output = new Output(this.screen, this.main);
      evaluate = function(it){
        if (!it.length) {
          this$.output.Set();
        }
        return this$.interpret.Run(it, function(err, stdout){
          return this$.output.Set(err || stdout);
        });
      };
      if (process.argv[2] === '--live') {
        this.prompt.on('changed', __.throttle(evaluate, 1000));
      }
      this.prompt.on('run', evaluate);
      return this.screen.render();
    };
    return LiveShell;
  }());
  module.exports = new LiveShell;
}).call(this);
